# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: 975881140b95941878b25726a3d0996ed3aacf84 # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  
  addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: 975881140b95941878b25726a3d0996ed3aacf84 # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
  
  SonarScanner.MSBuild.exe begin /k:"andypere_devops-today" /d:sonar.organization="andypere-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="975881140b95941878b25726a3d0996ed3aacf84"
  MsBuild.exe /t:Rebuild
  SonarScanner.MSBuild.exe end /d:sonar.login="975881140b95941878b25726a3d0996ed3aacf84"
